FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

RUN /bin/sh -c "pip install --no-cache-dir setuptools"
RUN /bin/sh -c "pip install --no-cache-dir neutron-zvm-plugin"
RUN /bin/sh -c "pip install --no-cache-dir zvmcloudconnector"

RUN mkdir -p /etc/zvmsdk
RUN touch /etc/zvmsdk/token.dat
RUN chmod 755 -R /etc/zvmsdk

USER neutron